mizarlib
git-svn-id: https://www.lri.fr/svn/demons/why2/trunk@1724 ecafba89-7d34-45a1-8a0b-92829e960b72

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1959,9 +1959,9 @@ echo "${ECHO_T}$MIZARLIB" >&6
 	echo "$as_me:$LINENO: result: $MIZARLIB" >&5
 echo "${ECHO_T}$MIZARLIB" >&6
     else
-	{ { echo "$as_me:$LINENO: error: Cannot find Mizar library; please set \$MIZFILES" >&5
-echo "$as_me: error: Cannot find Mizar library; please set \$MIZFILES" >&2;}
-   { (exit 1); exit 1; }; }
+	{ echo "$as_me:$LINENO: WARNING: Cannot find Mizar library; please set \$MIZFILES" >&5
+echo "$as_me: WARNING: Cannot find Mizar library; please set \$MIZFILES" >&2;}
+	MIZAR=no
     fi
     fi
 fi
