typage pour Simplify
git-svn-id: https://www.lri.fr/svn/demons/why2/trunk@610 ecafba89-7d34-45a1-8a0b-92829e960b72

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -999,7 +999,7 @@ else
 fi
 
     if test "$COQDEP" = true ; then
-	echo "configure: warning: Cannot find coqdep." 1>&2
+	{ echo "configure: error: Cannot find coqdep." 1>&2; exit 1; }
     fi
     COQLIB=`coqc -where`
 
