Abort configuration if octagon's one fails
git-svn-id: https://www.lri.fr/svn/demons/why2/trunk@1772 ecafba89-7d34-45a1-8a0b-92829e960b72

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1701,8 +1701,15 @@ fi
 
 
 # Octagon library
-(cd octagon; ./configure --with-num=float --with-ocaml=$OCAMLLIB;
- chmod 755 oct-config)
+cd octagon
+./configure --with-num=float --with-ocaml=$OCAMLLIB
+if test $? -ne 0 ; then
+   { { echo "$as_me:$LINENO: error: problem with octagon configuration (did you install g++ ?)" >&5
+echo "$as_me: error: problem with octagon configuration (did you install g++ ?)" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+chmod 755 oct-config
+cd ..
 
 # camlp4
 # Extract the first word of "camlp4o", so it can be a program name with args.
