but tout entier dans le .wol en syntaxe Coq
git-svn-id: https://www.lri.fr/svn/demons/why2/trunk@400 ecafba89-7d34-45a1-8a0b-92829e960b72

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -566,8 +566,8 @@ OCAMLLIB=`$OCAMLC -v | tail -1 | cut -f 4 -d " "`
 echo "ocaml library path is $OCAMLLIB"
 
 case $OCAMLVERSION in
-  0.*|1.*|2.00|3.00*)
-        { echo "configure: error: You need Objective 3.01 or later" 1>&2; exit 1; };;
+  0.*|1.*|2.00|3.00*|3.01*|3.02*|3.03*|3.04*)
+        { echo "configure: error: You need Objective 3.06 or later" 1>&2; exit 1; };;
 esac
 
 
