bench
git-svn-id: https://www.lri.fr/svn/demons/why2/trunk@1710 ecafba89-7d34-45a1-8a0b-92829e960b72

diff --git a/bench/c/bench b/bench/c/bench
--- a/bench/c/bench
+++ b/bench/c/bench
@@ -116,18 +116,27 @@ cd ../good
 export CADUCEUSLIB=`pwd`/../../../lib
 
 bench_c_good () {
-    options="$1 -why-opt -split-user-conj --typing-predicates"
+    options="$1 -why-opt -split-user-conj"  # --typing-predicates"
     echo "-------------------------------------------------------------------"
-    echo "Bench Caduceus+Simplify avec options: $options"
+    echo "Bench Caduceus+Simplify/Yices with options: $options"
     parsing="../../../bin/caduceus.opt $options"
 
     rm -f why/*.why
     rm -f simplify/*_why.sx
+    rm -f smtlib/*_why.smt
+    VCS=""
     for f in $FILES; do
-	echo -n "  Generating simplify VCG for $f.c... "
+	echo -n "  Generating VCs for $f.c... "
 	if $parsing  $f.c > /tmp/caduceus.tmp 2>&1; then
 	    if $make -f $f.makefile simplify/${f}_why.sx > /tmp/caduceus.tmp 2>&1 ; then
-		echo "ok"
+		if $make -f $f.makefile smtlib/${f}_why.smt > /tmp/caduceus.tmp 2>&1 ; then
+		    VCS="$VCS simplify/${f}_why.sx smtlib/${f}_why.smt"    
+		    echo "ok"
+		else
+		    echo "why FAILED :"
+		    cat /tmp/caduceus.tmp
+		    exit 1
+		fi
 	    else
 		echo "why FAILED :"
 		cat /tmp/caduceus.tmp
@@ -139,7 +148,7 @@ bench_c_good () {
 	    exit 1
 	fi
     done
-    ../../../bin/dp.opt -timeout 20 simplify/*_why.sx 2>/dev/null || true
+    ../../../bin/dp.opt -timeout 20 $VCS 2>/dev/null || true
 }
 
 bench_c_good
