*** empty log message ***
git-svn-id: https://www.lri.fr/svn/demons/why2/trunk@1218 ecafba89-7d34-45a1-8a0b-92829e960b72

diff --git a/bench/c/bench b/bench/c/bench
--- a/bench/c/bench
+++ b/bench/c/bench
@@ -123,8 +123,13 @@ rm -f simplify/*_why.sx.all
 for f in $FILES; do
     echo -n "  Generating simplify VCG for $f.c... "
     if $parsing  $f.c > /tmp/caduceus.tmp 2>&1; then
-        make -f $f.makefile simplify/${f}_why.sx.all > /tmp/caduceus.tmp 2>&1
-	echo "ok"
+        if make -f $f.makefile simplify/${f}_why.sx.all > /tmp/caduceus.tmp 2>&1 ; then
+	    echo "ok"
+	else
+	   echo "why FAILED :"
+	   cat /tmp/caduceus.tmp
+	   exit 1
+	fi
     else
 	echo "caduceus FAILED (rejected a good file) :"
 	cat /tmp/caduceus.tmp
