reads/writes/raises mots cles / parseur C
git-svn-id: https://www.lri.fr/svn/demons/why2/trunk@637 ecafba89-7d34-45a1-8a0b-92829e960b72

diff --git a/bench/c/bench b/bench/c/bench
--- a/bench/c/bench
+++ b/bench/c/bench
@@ -3,7 +3,7 @@
 # benchmark for caduceus
 
 # C files to parse with success
-echo "C parsing"
+echo "C parsing (good)"
 cd good/syntax
 parsing="../../../../bin/caduceus.opt -parse-only"
 for f in *.c; do
@@ -16,8 +16,29 @@ for f in *.c; do
     echo -n "GCC ok... "
     if ! $parsing  $f > /dev/null 2>&1; then
 	echo "caduceus FAILED"
-	$parsing $f
+	#$parsing $f
+	#exit 1
+    else
+	echo "caduceus ok... "
+    fi
+done
+
+echo "C parsing (bad)"
+cd ../../bad-syn
+parsing="../../../bin/caduceus.opt -parse-only"
+for f in *.c; do
+    echo -n "  "$f"... "
+    if gcc -c $f > /dev/null 2>&1; then
+	echo "GCC failed (accepted a bad file)"
+	gcc -c $f
 	exit 1
     fi
-    echo "caduceus ok... "
+    echo -n "GCC ok... "
+    if $parsing  $f > /dev/null 2>&1; then
+	echo "caduceus FAILED (accepted a bad file)"
+	#$parsing $f
+	#exit 1
+    else
+	echo "caduceus ok... "
+    fi
 done
