on ne vérifie plus les preuves Coq
git-svn-id: https://www.lri.fr/svn/demons/why2/trunk@1546 ecafba89-7d34-45a1-8a0b-92829e960b72

diff --git a/bench/c/bench b/bench/c/bench
--- a/bench/c/bench
+++ b/bench/c/bench
@@ -136,29 +136,29 @@ for f in $FILES; do
 done
 ../../../bin/dp.opt -timeout 20 simplify/*_why.sx 2>/dev/null || true
 
-
-for f in $FILES; do
-    echo -n "  $f.c... "
-    rm -f coq/caduceus_spec_why.v
-    if $parsing  $f.c > /tmp/caduceus.tmp 2>&1; then
-	echo -n "caduceus ok... "
-	if $make -f $f.makefile coq > /tmp/caduceus.tmp 2>&1; then
-	    n=`grep -c Admitted coq/${f}_why.v`
-	    if test $n -ne 0 ; then
-		echo "Coq proof ok (with $n Admitted)... "
-	    else
-		echo "Coq proof ok... "
-	    fi
-	else
-	    echo "Coq proof FAILED !"
-	    cat /tmp/caduceus.tmp
-	    exit 1
-	fi
-    else
-	echo "caduceus FAILED (rejected a good file) :"
-	cat /tmp/caduceus.tmp
-	exit 1
-    fi
-done
+# Coq proofs
+# for f in $FILES; do
+#     echo -n "  $f.c... "
+#     rm -f coq/caduceus_spec_why.v
+#     if $parsing  $f.c > /tmp/caduceus.tmp 2>&1; then
+# 	echo -n "caduceus ok... "
+# 	if $make -f $f.makefile coq > /tmp/caduceus.tmp 2>&1; then
+# 	    n=`grep -c Admitted coq/${f}_why.v`
+# 	    if test $n -ne 0 ; then
+# 		echo "Coq proof ok (with $n Admitted)... "
+# 	    else
+# 		echo "Coq proof ok... "
+# 	    fi
+# 	else
+# 	    echo "Coq proof FAILED !"
+# 	    cat /tmp/caduceus.tmp
+# 	    exit 1
+# 	fi
+#     else
+# 	echo "caduceus FAILED (rejected a good file) :"
+# 	cat /tmp/caduceus.tmp
+# 	exit 1
+#     fi
+# done
 
 
