Monad.apply; verif alias
git-svn-id: https://www.lri.fr/svn/demons/why2/trunk@83 ecafba89-7d34-45a1-8a0b-92829e960b72

diff --git a/bench/bench b/bench/bench
--- a/bench/bench
+++ b/bench/bench
@@ -27,8 +27,13 @@ goods () {
 bads () {
     for f in $1/*.ml; do
 	echo -n "  "$f"... "
-	if $pgm $2 $f > /dev/null 2>&1; 
-        then echo "FAILED!"; exit 1; else echo "ok"; fi
+	if $pgm $2 $f > /dev/null 2>&1; then 
+	    echo "$pgm $2 $f"
+	    echo "FAILED!"
+	    exit 1 
+        else 
+	    echo "ok"
+	fi
     done
 }
 
