compat ocaml 3.08
git-svn-id: https://www.lri.fr/svn/demons/why2/trunk@984 ecafba89-7d34-45a1-8a0b-92829e960b72

diff --git a/bench/bench.in b/bench/bench.in
--- a/bench/bench.in
+++ b/bench/bench.in
@@ -25,11 +25,11 @@ provers () {
 	$coqc "$base"_why.v
 	exit 1
     fi
-    if ! $coqc -I $dir "$base"_valid.v > /dev/null 2>&1; then
-	echo "coq validation FAILED"
-	$coqc -I $dir "$base"_valid.v
-	exit 1
-    fi
+#      if ! $coqc -I $dir "$base"_valid.v > /dev/null 2>&1; then
+#  	echo "coq validation FAILED"
+#  	$coqc -I $dir "$base"_valid.v
+#  	exit 1
+#      fi
     echo -n "coq ok... "
     # running PVS
     if ! $pgm --pvs $f > /dev/null 2>&1; then
