Logic.term: on conserve un noeud deref pour l'acces !x; supprime par unref_term dans les parties logiques
git-svn-id: https://www.lri.fr/svn/demons/why2/trunk@318 ecafba89-7d34-45a1-8a0b-92829e960b72

diff --git a/bench/bench b/bench/bench
--- a/bench/bench
+++ b/bench/bench
@@ -13,8 +13,17 @@ goods () {
 	    echo -n "why ok... "
 	    if $coqc "$base"_why.v > /dev/null 2>&1; then
 		echo "coq ok"
+#  		echo -n "coq ok..."
+#  		$pgm --ocaml --ocaml-ext $f > $base.ml 2>/dev/null
+#  		if ocamlc -c $base.ml > /dev/null 2>&1; then
+#  		    echo "ocaml ok"
+#  		else
+#  		    echo "ocaml FAILED"
+#  		fi
 	    else
 		echo "coq FAILED"
+		$coqc "$base"_why.v
+		exit 1
 	    fi
 	else 
 	    echo "why FAILED"
