PVS: le bench teste maintenant le type-checking; output repare; librairie
git-svn-id: https://www.lri.fr/svn/demons/why2/trunk@412 ecafba89-7d34-45a1-8a0b-92829e960b72

diff --git a/bench/bench b/bench/bench
--- a/bench/bench
+++ b/bench/bench
@@ -5,14 +5,51 @@
 pgm=$1
 coqc="coqc -R ../lib/coq Coq.why"
 
-goods () {
+pvstc () {
+    context=`dirname $1`
+    theory=`basename $1`
+    cd $context
+    echo "(typecheck "'"'$theory'"'")" > pvstc.el
+    pvs -q -batch -l pvstc.el
+    cd ..
+}
+
+provers () {
+    file=$1
+    base=$2
+    # running Coq
+    if ! $coqc "$base"_why.v > /dev/null 2>&1; then
+	echo "coq FAILED"
+	$coqc "$base"_why.v
+	exit 1
+    fi
+    echo -n "coq ok... "
+    # running PVS
+    if ! $pgm --pvs $f > /dev/null 2>&1; then
+	echo "pvs generation FAILED"
+	$pgm --pvs $f
+	exit 1
+    fi
+    if ! pvstc "$base"_why > /dev/null 2>&1; then
+	echo "pvs typecheck FAILED"
+	pvs -q -v 3 -batch -l pvstc.el
+	exit 1
+    fi
+    echo "pvs ok"
+}
+
+good_ml () {
     for f in $1/*.mlw; do
 	echo -n "  "$f"... "
 	base=$1/`basename $f .mlw`
-	if $pgm --coq $f > /dev/null 2>&1; then
-	    echo -n "why ok... "
-	    if $coqc "$base"_why.v > /dev/null 2>&1; then
-		echo "coq ok"
+	# running Why
+	if ! $pgm --coq $f > /dev/null 2>&1; then
+	    echo "why FAILED"
+	    $pgm --coq $f
+	    exit 1
+	fi
+	echo -n "why ok... "
+	provers $f $base
 #  		echo -n "coq ok..."
 #  		$pgm --ocaml --ocaml-ext $f > $base.ml 2>/dev/null
 #  		if ocamlc -c $base.ml > /dev/null 2>&1; then
@@ -20,20 +57,10 @@ goods () {
 #  		else
 #  		    echo "ocaml FAILED"
 #  		fi
-	    else
-		echo "coq FAILED"
-		$coqc "$base"_why.v
-		exit 1
-	    fi
-	else 
-	    echo "why FAILED"
-	    $pgm --coq $f
-	    exit 1
-	fi
     done
 }
 
-goods_c () {
+good_c () {
     for f in $1/*.c; do
 	echo -n "  "$f"... "
 	base=$1/`basename $f .c`
@@ -49,12 +76,7 @@ goods_c () {
 	    exit 1
 	fi
 	echo -n "why ok... "
-	if ! $coqc "$base"_why.v > /dev/null 2>&1; then
-	    echo "coq FAILED"
-	    $coqc "$base"_why.v
-	    exit 1
-	fi
-	echo "coq ok"
+	provers $f $base
     done
 }
 
@@ -71,7 +93,7 @@ bads () {
     done
 }
 
-if test "$2" == "c"; then goods_c good-c; exit 0; fi
+if test "$2" == "c"; then good_c good-c; exit 0; fi
 
 # 1. Syntax
 echo "=== Checking parsing errors ==="
@@ -90,12 +112,12 @@ echo ""
 
 # 3. ML benchmark
 echo "=== Checking good files ==="
-goods good
+good_ml good
 echo ""
 
 # 4. C benchmark
 echo "=== Checking good C files ==="
-goods_c good-c
+good_c good-c
 
 exit 0
 
diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -932,7 +932,7 @@ fi
 #  	fi
 #  fi
 
-# coq
+# Coq
 # Extract the first word of "coqc", so it can be a program name with args.
 set dummy coqc; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
@@ -964,12 +964,14 @@ else
 fi
 
 if test "$COQC" = no ; then
-	{ echo "configure: error: Cannot find coqc." 1>&2; exit 1; }
-fi
-# Extract the first word of "coqdep", so it can be a program name with args.
+    COQ=no
+    echo "configure: warning: Cannot find coqc." 1>&2
+else
+    COQ=yes
+    # Extract the first word of "coqdep", so it can be a program name with args.
 set dummy coqdep; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:973: checking for $ac_word" >&5
+echo "configure:975: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_COQDEP'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -996,27 +998,72 @@ else
   echo "$ac_t""no" 1>&6
 fi
 
-if test "$COQDEP" = true ; then
+    if test "$COQDEP" = true ; then
 	echo "configure: warning: Cannot find coqdep." 1>&2
+    fi
+    COQLIB=`coqc -where`
+
+    echo $ac_n "checking Coq version""... $ac_c" 1>&6
+echo "configure:1008: checking Coq version" >&5
+    COQVERSION=`coqc -v | sed -n -e 's|.*version* *\([^ ]*\) .*$|\1|p' `
+
+    case $COQVERSION in
+    7.3)
+	echo "$ac_t""$COQVERSION" 1>&6
+	cp -f lib/coq/WhyCoq73.v lib/coq/WhyCoqCompat.v;;
+    7.3*)
+	echo "$ac_t""$COQVERSION" 1>&6
+	cp -f lib/coq/WhyCoqDev.v lib/coq/WhyCoqCompat.v;;
+    *)
+	COQ=no
+	echo "configure: warning: You need Coq 7.3 or later; Coq discarded" 1>&2;;
+    esac
 fi
-COQLIB=`coqc -where`
 
-echo $ac_n "checking Coq version""... $ac_c" 1>&6
-echo "configure:1006: checking Coq version" >&5
-COQVERSION=`coqc -v | sed -n -e 's|.*version* *\([^ ]*\) .*$|\1|p' `
+# PVS
+# Extract the first word of "pvs", so it can be a program name with args.
+set dummy pvs; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:1028: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_prog_PVSC'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  if test -n "$PVSC"; then
+  ac_cv_prog_PVSC="$PVSC" # Let the user override the test.
+else
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
+  ac_dummy="$PATH"
+  for ac_dir in $ac_dummy; do
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      ac_cv_prog_PVSC="pvs"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+  test -z "$ac_cv_prog_PVSC" && ac_cv_prog_PVSC="no"
+fi
+fi
+PVSC="$ac_cv_prog_PVSC"
+if test -n "$PVSC"; then
+  echo "$ac_t""$PVSC" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
 
-case $COQVERSION in
-  7.3)
-    echo "$ac_t""$COQVERSION" 1>&6
-    cp -f lib/coq/WhyCoq73.v lib/coq/WhyCoqCompat.v;;
-  7.3*)
-    echo "$ac_t""$COQVERSION" 1>&6
-    cp -f lib/coq/WhyCoqDev.v lib/coq/WhyCoqCompat.v;;
-  *)
-    { echo "configure: error: You need Coq 7.3 or later" 1>&2; exit 1; };;
-esac
+if test "$PVSC" = no ; then
+    PVS=no
+    echo "configure: warning: Cannot find PVS." 1>&2
+else
+    PVS=yes
+fi
 
 # substitutions to perform
+
+
+
+
+
 
 
 
@@ -1189,11 +1236,14 @@ s%@OCAMLWEB@%$OCAMLWEB%g
 s%@CAMLP4O@%$CAMLP4O%g
 s%@COQC@%$COQC%g
 s%@COQDEP@%$COQDEP%g
+s%@PVSC@%$PVSC%g
 s%@OCAMLBEST@%$OCAMLBEST%g
 s%@OCAMLVERSION@%$OCAMLVERSION%g
 s%@OCAMLLIB@%$OCAMLLIB%g
 s%@CAMLP4LIB@%$CAMLP4LIB%g
+s%@COQ@%$COQ%g
 s%@COQLIB@%$COQLIB%g
+s%@PVS@%$PVS%g
 
 CEOF
 EOF
