*** empty log message ***
git-svn-id: https://www.lri.fr/svn/demons/why2/trunk@1043 ecafba89-7d34-45a1-8a0b-92829e960b72

diff --git a/examples-c/Makefile b/examples-c/Makefile
--- a/examples-c/Makefile
+++ b/examples-c/Makefile
@@ -1,8 +1,15 @@
 
-DIRS = tutorial sorting
+DIRS = tutorial sorting linked-lists
 
 all: 
-	for d in $(DIRS); do make -C $$d coq; done
+	for d in $(DIRS); do \
+		if make -C $$d coq; then \
+			echo "Coq proofs OK in $$d" ; \
+		else \
+			echo "Coq proofs FAILED in $$d" ; \
+			exit 1 ;\
+		fi ; \
+	done
 
 clean:
 	for d in $(DIRS); do make -C $$d clean; done
