java
git-svn-id: https://www.lri.fr/svn/demons/why2/trunk@2598 ecafba89-7d34-45a1-8a0b-92829e960b72

diff --git a/bench/java/bench b/bench/java/bench
--- a/bench/java/bench
+++ b/bench/java/bench
@@ -97,20 +97,14 @@ bench_java_good () {
 	if $parsing  $f.java > /tmp/krakatoa.tmp 2>&1; then
 	    if $jessie  $f.jc > /tmp/krakatoa.tmp 2>&1; then
 		if $make -f $f.makefile simplify/${f}_why.sx > /tmp/krakatoa.tmp 2>&1 ; then
-#		    if $make -f $f.makefile smtlib/${f}_why.smt > /tmp/krakatoa.tmp 2>&1 ; then
-			if $make -f $f.makefile why/${f}_why.why > /tmp/krakatoa.tmp 2>&1 ; then
-			    VCS="$VCS simplify/${f}_why.sx smtlib/${f}_why.smt why/${f}_why.why"    
-			    echo "ok"
-			else
-			    echo "why FAILED :"
-			    cat /tmp/krakatoa.tmp
-			    exit 1
-			fi
-#		    else
-#			echo "why FAILED :"
-#			cat /tmp/krakatoa.tmp
-#			exit 1
-#		    fi
+		    if $make -f $f.makefile why/${f}_why.why > /tmp/krakatoa.tmp 2>&1 ; then
+			VCS="$VCS simplify/${f}_why.sx why/${f}_why.why"    
+			echo "ok"
+		    else
+			echo "why FAILED :"
+			cat /tmp/krakatoa.tmp
+			exit 1
+		    fi
 		else
 		    echo "why FAILED :"
 		    cat /tmp/krakatoa.tmp
